// -> NextJS
import { Sora } from "next/font/google";

// -> Utils
import { cn } from "@/lib/utils";

// -> Styles CSS
import "./globals.css";

// -> Types
import type { Metadata } from "next";

// -> Components
import { MenuDesktop } from "@/components/menu/menu-desktop";
import { MenuMobile } from "@/components/menu/menu-mobile";

const soraFont = Sora({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full w-full">
      <body 
        className={cn(
          'flex flex-col flex-1 w-full h-full bg-background lg:gap-2',
          soraFont.className
        )}
      >
        <section className="w-full min-h-16">
          <MenuMobile />
          <MenuDesktop />
        </section>

        <section className="flex flex-1 w-full max-w-[1304px] h-full px-3 m-auto">
          {children}
        </section>
      </body>
    </html>
  );
}
