// -> NextJS
import { Poppins } from "next/font/google";

// -> Utils
import { cn } from "@/lib/utils";

// -> Styles CSS
import "./globals.css";

// -> Types
import type { Metadata } from "next";

const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full w-full">
      <body 
        className={cn(
          'flex flex-1 w-full h-full bg-zinc-950 text-zinc-100',
          poppins.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
